### ISSUE TITLE
Slash Commands not loaded

### ISSUE THREAD

**Issue by Sothirich** [Comet-Development/Discord.js-v14-commands-handler#1]
```
DiscordAPIError[20012]: You are not authorized to perform this action on this application
    at SequentialHandler.runRequest (C:\Users\QikKenzz\OneDrive\Code\DiscordBot_v14\node_modules\@discordjs\rest\dist\index.js:708:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\QikKenzz\OneDrive\Code\DiscordBot_v14\node_modules\@discordjs\rest\dist\index.js:511:14)
    at async C:\Users\QikKenzz\OneDrive\Code\DiscordBot_v14\Handlers\slashCommand.js:46:5 {
  rawError: {
    message: 'You are not authorized to perform this action on this application',
    code: 20012
  },
  code: 20012,
  status: 403,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/976111871524470866/guilds/856438675943194674/commands',
  requestBody: {
    files: undefined,
    json: [ [Object], [Object], [Object], [Object] ]
  }
}
```

**Comment by lynxdevv** [comment]
Hey there,

Remove the GUILD_ID from .env file and try it!

**Comment by lynxdevv** [comment]
reinvite the bot to the server with application.commands scope

**Comment by Sothirich** [comment]
nope, still the same

**Comment by lynxdevv** [comment]
You have used a different client.id. please use client id and token of a same application.

If not working let me know about it!

**Comment by Sothirich** [comment]
ohh my badd.. i pasted wrong ID >,,<

**Comment by NotSoMik** [comment]
Dont try to claim other people works lmao, credits https://github.com/Nathaniel-VFX/Discord.js-v14-Command-Handlers

**Comment by lynxdevv** [comment]
> Dont try to claim other people works lmao, credits https://github.com/Nathaniel-VFX/Discord.js-v14-Command-Handlers

Hey there,

I just got ideas from his handler. I have built this on my own with my friend.
We just referred and added many changed and custom settings to the code. if u cant believe u can check it out.

**Comment by lynxdevv** [comment]
> ohh my badd.. i pasted wrong ID >,,<

No issues!
